services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    depends_on:
      - redis
    volumes:
      - .data:/usr/src/app/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
