### 
GET http://localhost:3000/api/tags

### 
POST http://localhost:3000/api/tags
Content-Type: application/json

{
    "name": "Priority"
}

### 
# Assign tag 1 and 2 to task 1
POST http://localhost:3000/api/tags/assign
Content-Type: application/json

{
    "taskId": 1,
    "tagIds": [1, 2]
}

### 
GET http://localhost:3000/api/tags/tasks-with-tags
