### Drill 1: Category Operations

### 1. List Categories
GET http://localhost:3000/api/categories

### 2. Create Category
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Urgent",
    "color": "red"
}

### 3. Get Stats (Tasks per Category)
GET http://localhost:3000/api/categories/stats
